baseURL = "https://blog.ryanwcummings.com/"
languageCode = "en-us"
title = "RC"
theme = "hyde-hyde"
googleAnalytics = "UA-124665888-1"
builddrafts = false
paginate = 10

## Site Settings
[params]
    author = "Ryan Cummings"
    description = "At the intersection of medicine, tech, and philosophy"
    authorimage = "/img/site/profile.jpg"
    dateformat = "Jan 2, 2006"

    # sidebar, copyright & license
    copyright = "Ryan Cummings"
    license = "CC BY-SA 4.0"
    licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    showBuiltWith = true

    relatedPosts = true
    enableRobotsTXT = true
    enableEmoji = true

    highlightjs = true
    highlightjsstyle = "zenburn"
    highlightjslanguages = ["cmake", "lisp", "elisp"]

    #toc = "tocbot"
    mainSections = "posts"

[params.social]
    github = "ryancummings"
    facebook = "updog"
    instagram = "muchinstamanygramwow"
    email = "rcummings.04@gmail.com"

## Main Menu
[[menu.main]]
    name = "Home"
    identifier = "home"
    weight = 50
    url = "/"

[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 100
    url = "/pages/about/"

[[menu.main]]
    name = "Projects"
    identifier = "projects"
    weight = 150
    url = "/pages/projects/"

[[menu.main]]
    name = "Links"
    identifier = "links"
    weight = 150
    url = "/pages/links/"

[[menu.main]]
    name = "Blog Posts"
    weight = 200
    identifier = "posts"
    url = "/posts/"

[[menu.main]]
    name = "Categories"
    weight = 200
    identifier = "categories"
    url = "/categories/"

[[menu.main]]
    name = "Tags"
    weight = 200
    identifier = "tags"
    url = "/tags/"
